name: Publish Maven Calculator Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  DeployMavenPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deploy Package
        run : mvn deploy