name: Publish Maven Calculator Package

env:
  PASS_TOKEN: ${{ secrets.PASS_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  DeployMavenPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set ENV
        run:  export PASS_TOKEN=${PASS_TOKEN}
      - name: Deploy Package
        run : mvn deploy