name: Publish Maven Calculator Package

env:
  PASS_TOKEN: ${{ secrets.PASS_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish Package
        run : mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}